### ISSUE TITLE
Running an image built in previous step doesn't work anymore

### ISSUE THREAD

**Issue by shakib609** [addnab/docker-run-action#13]
This part of the documentation does not work as expected anymore.
```yml
- uses: docker/build-push-action@v1
  with:
    repository: test-image
    push: false
- uses: addnab/docker-run-action@v3
  with:
    image: test-image:latest
    run: echo "hello world"
```

`docker/build-push-action` gives the below warning while running action.
```
Warning: Input 'repository' has been deprecated with message: v2 is now available through docker/build-push-action@v2
```

**Comment by addnab** [comment]
Thanks. I've updated the README.

**Comment by pmoosh** [comment]
Question I am using the example and it fails with:
docker: Error response from daemon: pull access denied for test-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Am I missing something?

**Comment by winghouchan** [comment]
@pmoosh: you likely need to specify `load: true` for `build-push-action`. For example:

```
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: <your-tag>
          load: true
          push: false
```

I discovered this when I was trying to debug the same issue you were having. Running [`docker images`](https://docs.docker.com/engine/reference/commandline/images/) didn't list the tagged image. I happened to decide to read the [documentation for `docker buildx build`](https://docs.docker.com/engine/reference/commandline/buildx_build/) and found the following:

> ### Load the single-platform build result to docker images (`--load`)
> 
> Shorthand for [`--output=type=docker`](https://docs.docker.com/engine/reference/commandline/buildx_build/#docker). Will automatically load the single-platform build result to `docker images`.

In [documentation for `build-push-action`](https://github.com/docker/build-push-action#inputs), the default for `load` is `false`.

@addnab: maybe the [example in the README](https://github.com/addnab/docker-run-action/blob/main/README.md#run-an-image-built-by-a-previous-step) could be updated?

```diff
#### run an image built by a previous step
```yaml
– uses: docker/build-push-action@v2
  with:
    tags: test-image:latest
    push: false
+   load: true
– uses: addnab/docker-run-action@v3
  with:
    image: test-image:latest
    run: echo "hello world"
```
