### ISSUE TITLE
docker-run-action doesn't honor ENTRYPOINT defined in Dockerfile

### ISSUE THREAD

**Issue by yfarjoun** [addnab/docker-run-action#14]
I have a docker file that has a rather complex ENTRYPOINT set up so that when invokes it runs the provided command inside a conda environment. 

When I try to use the docker-run-action to test the container in a github-action, it fails but this is because it seems that the entrypoint is redefined in the invocation. 

It would be nice if there was a way to avoid redefining the entry point for images that have been designed this way.

Cheers!

**Comment by addnab** [comment]
@yfarjoun if possible, can you share the workflow config that you used for your action? If it's not public, can you simply share a snippet?

I believe you're likely seeing this error because the image input you provided to this action is likely empty. It should still work if you have a complex entrypoint already defined.

**Comment by yfarjoun** [comment]
I'm trying to run
```yaml
      -
        uses: addnab/docker-run-action@v3
        with:
          image: "richardslab/template_r_project:latest"
          run: conda env list
```

but my entrypoint in richardslab/template_r_project:latest
is 
```Dockerfile
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["echo", "need to provide a command..."]
```
where `entrypoint.sh` is:

```bash
#!/bin/bash
conda run -n Template --no-capture-output "$@"
```

**Comment by addnab** [comment]
This might be hacky but can you run it with the "shell" input like so

```yaml
-
        uses: addnab/docker-run-action@v3
        with:
          image: "richardslab/template_r_project:latest"
          shell: /usr/local/bin/entrypoint.sh
          run: conda env list
```

**Comment by addnab** [comment]
This might be hacky but can you run it like so

```yaml
-
        uses: addnab/docker-run-action@v3
        with:
          image: "richardslab/template_r_project:latest"
          run: /usr/local/bin/entrypoint.sh conda env list
```

Or

```yaml
-
        uses: addnab/docker-run-action@v3
        with:
          image: "richardslab/template_r_project:latest"
          shell: /usr/local/bin/entrypoint.sh 
          run: conda env list
```
