### ISSUE TITLE
Pass default env variables set by github to the docker

### ISSUE THREAD

**Issue by shreyaspurohit** [addnab/docker-run-action#19]
I would like to use the default env vars set by the Github Actions as defined here - https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables - in the docker. Right now, these are not being set. It can be verified by executing `printenv` in the shell.

**Comment by pangteypiyush** [comment]
Environment variables are passed down to the action container, which you can verify from the job logs:

`/usr/bin/docker run <REDACTED> -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF`

This docker container action creates your container using: https://github.com/addnab/docker-run-action/blob/main/entrypoint.sh#L11
So, in order to pass these env variables further, you have to explicitly define them in `options`:

```yaml
      - uses: addnab/docker-run-action@v3
        with:
          image: alpine:latest
          options: -v ${{ github.workspace }}:/home -e FOO -e GITHUB_REF
          run: |
            echo foo $FOO
            echo REF $GITHUB_REF
        env:
          FOO: BAR
```

**Comment by shreyaspurohit** [comment]
Got it, thanks

**Comment by orihomie** [comment]
@pangteypiyush hi, have u tried your method with gh actions variables? I mean to pass `needs.job.output.somevar` to this action as an environment variable?

**Comment by pangteypiyush** [comment]
@orihomie this?

```
      - uses: addnab/docker-run-action@v3
        env:
          SOMEVAR: ${{ needs.job.outputs.somevar }}
        with:
          image: alpine:latest
          options: -e SOMEVAR
          run: |
            echo $SOMEVAR
```
