### ISSUE TITLE
docker-run-action doesn't HONOR login step happened before

### ISSUE THREAD

**Issue by orihomie** [addnab/docker-run-action#20]
Hi, if I use docker login step somethere before that action, docker-run-action fails if I omit user & password params

```
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.login }}
          password: ${{ secrets.password }}
          
    - name: Run 
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ secrets.registry }}
          image: ${{ secrets.registry }}/image:${{ secrets.image_tag }}
          options: --rm -i -v ${{ github.workspace }}:/app
          run: echo "Hi"

```

> docker: Error response from daemon: Head https://***/v2/mahimage/manifests/v0.0.1: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
