### ISSUE TITLE
How to pass or use variables which are external to a running container?

### ISSUE THREAD

**Issue by orihomie** [addnab/docker-run-action#21]
I have a problem with using some variables in a container,  passing them doesnt work neither by gh actions syntax `${{ }}`, neither by passing variables by option `-e --env service_name=$service_name`. 

I saw there is passing GITHUB_ENV to a run
```
/usr/bin/docker run --name a33c10e4e8e7590d943f4971e1dfe677bc911_413b5e --label 8a33c1 --workdir /github/workspace --rm -e team -e build_number -e svc_name -e namespace -e GITHUB_PATH -e GITHUB_ENV -e
```

But then when container runs, there are echoes of this vars and I'm getting this:
```
Team: 
Build number: 
Service name: 
Namespace: 
```

**Comment by orihomie** [comment]
I have a bit more specific case which drives me a bit crazy because I've already spent a day figuring out the reason and found none. 

build_and_test job
```
build_and_test:
    needs: get_services
    runs-on: ubuntu-latest

    outputs:
      build_number: ${{ steps.get_build_number.outputs.build_number }}
      service_name: ${{ env.service_name }}
```

publish job
```
- name: Step in docker
        uses: addnab/docker-run-action@v3
        env:
          TEAM: affiliates
          BUILD_NUMBER: ${{ needs.build_and_test.outputs.build_number }}
          SVC: ${{ needs.build_and_test.outputs.service_name }}
          NAMESPACE: ${{ steps.get_namespace.outputs.namespace }}
  
        with:
          username: ${{ secrets.login }}
          password: ${{ secrets.pwd }}
          registry: ${{ secrets.cr }}
          image: ${{ secrets.cr }}/my-image:${{ secrets.tag }}
          options: --rm -i -v ${{ github.workspace }}:/app -w=/app -e TEAM -e BUILD_NUMBER -e SVC -e NAMESPACE
          run: |
            echo "Team: ${TEAM}"
            echo "Build number: ${BUILD_NUMBER}"
            echo "Service name: ${SVC}"
            echo "Namespace: ${NAMESPACE}"
            
```

and output is
```
Team: affiliates
Build number: 9e9c5c8-qa
Service name: 
Namespace: pe-475
```

Why SVC is empty?
