### ISSUE TITLE
Mount volume main repository folder

### ISSUE THREAD

**Issue by avelino** [addnab/docker-run-action#4]
You must mount the repository volume

We don't usually use github actions to run standalone commands like `echo`

**Comment by addnab** [comment]
The README does have it documented [here](https://github.com/addnab/docker-run-action#use-docker-options). Sorry if it wasn't clear. Feel free to suggest any improvements to the docs.

```yml
- uses: addnab/docker-run-action@v1
  with:
    image: docker:latest
    options: -v $GITHUB_WORKSPACE:/work -e ABC=123
    run: |
      echo "first line"
```
