### ISSUE TITLE
Can't use with containerd

### ISSUE THREAD

**Issue by aakilin** [addnab/docker-run-action#40]
```
Run addnab/docker-run-action@v3
/home/ubuntu/bin/docker run --name d8b0ced24c48b43d178912d9831e_6122bb --label 765292 --workdir /github/workspace --rm -e "NAMESPACE" -e "ECR_REGISTRY" -e "REGION" -e "KUBECTL_VERSION" -e "ECR_REPOSITORY" -e "DOCKER_FILE" -e "ENVIRONMENT" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "INPUT_REGISTRY" -e "INPUT_IMAGE" -e "INPUT_OPTIONS" -e "INPUT_RUN" -e "INPUT_SHELL" -e "INPUT_USERNAME" -e "INPUT_PASSWORD" -e "INPUT_DOCKER_NETWORK" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/actions-runner/_work/_temp/_github_home":"/github/home" -v "/opt/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/opt/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/opt/actions-runner/_work/ExternalOrderAPI/ExternalOrderAPI":"/github/workspace" 765292:6236d8b0ced24c48b43d178912d9831e
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```
I've tried to add the option -v and use the correct docker.sock
```
      - name: Run Migrations
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ env.ECR_REGISTRY }}
          image: ${{ env.ECR_REPOSITORY }}:${{github.sha}}
          options: -v /run/containerd/containerd.sock:/var/run/docker.sock
          run: |
            ls -la
            python manage_custom.py showmigrations 2>&1
```
But it isn't working
What I have in the instance 
```
root@ip-10-20-2-26:~# ps aux | grep docker
ubuntu     10097  0.0  0.0 709352  7080 ?        Ssl  16:14   0:00 rootlesskit --net=vpnkit --mtu=1500 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/ubuntu/bin/dockerd-rootless.sh
ubuntu     10103  1.8  0.1 710248  9324 ?        Sl   16:14   0:54 /proc/self/exe --net=vpnkit --mtu=1500 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/ubuntu/bin/dockerd-rootless.sh
ubuntu     10129  0.6  0.7 1492896 61376 ?       Sl   16:14   0:18 dockerd
ubuntu     10144  0.1  0.4 1333968 38276 ?       Ssl  16:14   0:05 containerd --config /run/user/1000/docker/containerd/containerd.toml --log-level info
root       16687  0.0  0.9 1310044 79800 ?       Ssl  16:31   0:00 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root       34753  0.0  0.0   8168   720 pts/0    S+   17:04   0:00 grep --color=auto docker
```
