### ISSUE TITLE
FAILS on docker image containing forward slashes

### ISSUE THREAD

**Issue by tamis-laan** [addnab/docker-run-action#43]
Given the following with an image containing forward slashes:

``` yaml
    - name: Test
      uses: addnab/docker-run-action@v3
      with:
        image: /my/super/cool/image:latest
        run: |
          echo "HELLO WORLD" 
```

I get the following error:

```
invalid argument "echo \"HELLO WORLD\" " for "-c, --cpu-shares" flag: strconv.ParseInt: parsing "echo \"HELLO WORLD\" ": invalid syntax
See 'docker run --help'.
```
