### ISSUE TITLE
Mounting ${{ github.workspace }}

### ISSUE THREAD

**Issue by ghnp5** [addnab/docker-run-action#46]
Hello,

I'm trying something like this:

```
      - name: Test 1
        run: whoami > ${{ github.workspace }}/whoami.txt
      - name: Test 2
        uses: https://github.com/addnab/docker-run-action@v3
        with:
          image: docker:latest
          options: -v ${{ github.workspace }}:/work
          run: ls -la /work && echo "Test" > /work/test.log && ls -la /work
      - name: Test 3
        run: |
          ls -la ${{ github.workspace }}
          cat ${{ github.workspace }}/test.log
```

But `/work` doesn't seem to contain anything that is in `${{ github.workspace }}`

So I'm not understanding the first example in the README, where it gives the impression that mounting `${{ github.workspace }}` would let us pass files in the workspace to be used in other steps.

When running the `Test 2` step above, would it be possible to mount `${{ github.workspace }}`, write to a file in it, and have access to that file in the following steps?

This would be a good workaround for #41

Thanks!
