### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by enricorotundo** [addnab/docker-run-action#50]
Often I get the following error in GitHub Actions. Rerunning jobs would work sometimes but it's quite inconvenient.

```
Run addnab/docker-run-action@v3
  with:
    registry: docker.io
    image: xxxx/xxxx-xxxx:0.0.x
    options: xxxx
    run: xxxx

[...]
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Any fix/workaround to this?
