### ISSUE TITLE
Specify --rm with `docker run` to avoid cleanup issues with Gitea actions

### ISSUE THREAD

**Issue by CJLove** [addnab/docker-run-action#51]
I've been using this action in a workflow with Gitea actions, running an image with a volume mounted from the act_runner container:

```
      - name: Build
        uses: https://github.com/addnab/docker-run-action@v3
        with:
          image: myimage:mytag
          options: --volumes-from=${{ env.JOB_CONTAINER_NAME }}
          run: |
            g++ --version
```

On workflow exit an error is reported about a volume still being in use:
```
Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove GITEA-ACTIONS-TASK-push_WORKFLOW-ci_JOB-build-linux: volume is in use - [9f2c5c514906a56896158eae977a2d74f2e6eab97d03c97a3efa30c974dd8e69] (original error: <nil>) (original error: <nil>)
```

The container started by the `docker-run-action` is still there in `docker ps -a` output.

Adding a step to the workflow which runs `docker rm $(docker ps -l --format '{{.ID}}')` cleans this up.

I'm wondering whether specifying the `--rm` option in this action's  `entrypoint.sh` might clean this up more effectively.
