### ISSUE TITLE
Document usage with the metadata-action

### ISSUE THREAD

**Issue by oliv3r** [addnab/docker-run-action#57]
It is not uncommon to use the `metadata-action`. E.g.

```yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=auto
```
The idea of this is to generate the correct tag (if we are pushing a tag, otherwise a different tag gets created).

In such a case, how do we supply the image?

The build-and-push docker action uses the tag as
```yaml
tags: ${{ steps.meta.outputs.tags }}
```

which in the end, is sensible if we where intended to run a pushed container
```yaml
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
        run: |
```

But this is obviously wrong, so then how can we use this action? Two scenario's are to be thought of. Upon pushing of a tag, where the container is _also_ pushed into the ghcr, which is fine, and 'all other cases' e.g. pushes to master, pushes to a branch etc. How does this work, without pushing to ghcr and without using a fixed tag. (unless the answer is to always 'also' add a fixed tag, however that is done ...
