### ISSUE TITLE
Why can't --env-file find files in the github workspace?

### ISSUE THREAD

**Issue by red8888** [addnab/docker-run-action#58]
Why does this work: `-v ${{ github.workspace }}:/app`

But this does not? `--env-file=${{ github.workspace }}/gh.env`

```
      - id: get_gh_env
        run: |
          printenv | grep GITHUB_ > ${{ runner.temp }}/gh.env
          printenv | grep GITHUB_ > ${{ github.workspace }}/gh.env

      - id: sdfsdfsdfsdfsdfs
        uses: addnab/docker-run-action@v3
        with:
          image: sdfsdfs:sdfsdfsdf
          options: >-
            --env-file=${{ github.workspace }}/gh.env
            -v ${{ github.workspace }}:/app
        run: |
          do stuff
```

I get an error: `docker: open /home/runner/work/sdfsdf/sdfsdfs/gh.env: no such file or directory.`

Meanwhile I _can_ mount in the workspace and access all the files inside the container with `-v ${{ github.workspace }}:/app`.

So why can't it find a file in my workspace a pass to `--env-file`?

I also tried with runner temp files, but same issue can't find the file:  `--env-file=${{ runner.temp }}/gh.env`

**Comment by red8888** [comment]
I found I can just pass in the filename without the full path for the env file. I still dont understand why it works but it does:

```
      - id: sdfsdfsdfsdfsdfs
        uses: addnab/docker-run-action@v3
        with:
          image: sdfsdfs:sdfsdfsdf
          options: >-
            --env-file=gh.env
```
