### ISSUE TITLE
not passed cap-add docker option.

### ISSUE THREAD

**Issue by sergey-safarov** [addnab/docker-run-action#60]
I have defined actions like

```yaml
    - uses: addnab/docker-run-action@v3
      with:
        image: ${{some-image}}
        options: -v ${{ github.workspace }}:/usr/src/my-sources --cap-add chown 
        run: |
          cd /usr/src/my-sources
          chown -R user:group *
```
Where  ${{some-image}} executes the commands under `user` permissions. When docker process container starts with `--cap-add chown`, then this works without any issues. But this script generates errors like
```
chown: some_file: Operation not permitted
```
I have checked docker command in the actions logs and see volume mount passed properly, but `--cap-add chown` options are stripped.
Could you add the ability to pass `--cap-add` options?
